# Generated by Django 4.1 on 2022-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=40, verbose_name='Подразделение')),
                ('subject', models.CharField(max_length=40, verbose_name='Сотрудник')),
                ('fiz_face', models.CharField(max_length=40, verbose_name='Физ.лицо')),
                ('tabel_time', models.IntegerField(verbose_name='Табель учёта времени')),
            ],
            options={
                'verbose_name': 'Табель учёта рабочего времени',
            },
        ),
    ]
